experiment_name: 'chexpert_moco_pretrain_e2e_candid_ptx_classifier'
phase: 'classification'

lightning:
    trainer:
       gpus: '0'
       max_epochs: 50
       distributed_backend: 'dp'
       gradient_clip_val: 0.25
       lr: 1e-4
       precision: 16
    checkpoint_callback:
        monitor: 'val_loss'
        dirpath: './data/ckpt'
        save_last: true 
        mode: min
        save_top_k: 1
    early_stopping_callback:
        monitor: 'val_loss'
        min_delta: 0.00
        patience: 5
        verbose: False
        mode: 'min'
    logger:
        logger_type: 'WandbLogger'
        save_dir: './data/'
        project: 'gloria_candid_ptx_classifier'

model: 
    vision:
        model_name: 'moco_chexpert_densenet121'
        freeze_cnn: false
        pretrained: true
        num_targets: 3

data: 
    dataset: candid_ptx
    image:
        imsize: 256
    
transforms: 
    norm: 'half'
    random_crop:
        crop_size: 224

train: 
    batch_size: 64
    num_workers: 16
    loss_fn: 
        type: BCE
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'plateau'
        monitor: 'val_loss'
        interval: 'epoch'
        frequency: 3
